import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { report, sites, write } from '../scripts/set-version.mjs';

const SCRIPT = new URL('../scripts/set-version.mjs', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');

/** A minimal tree carrying the version at every site set-version.mjs knows
 * about, so tests exercise the real regexes against the real file shapes
 * without touching this checkout's own files. */
function makeTree(version) {
  const root = mkdtempSync(join(tmpdir(), 'hsot-ver-'));
  mkdirSync(join(root, 'src-tauri'), { recursive: true });
  writeFileSync(
    join(root, 'package.json'),
    `{\n  "name": "hs-offline-tracker",\n  "version": "${version}",\n  "private": true\n}\n`,
  );
  writeFileSync(
    join(root, 'src-tauri', 'tauri.conf.json'),
    `{\n  "productName": "HS Offline Tracker",\n  "version": "${version}",\n  "identifier": "io.falorfrozen.hsofflinetracker"\n}\n`,
  );
  writeFileSync(
    join(root, 'src-tauri', 'Cargo.toml'),
    `[package]\nname = "hs-offline-tracker"\nversion = "${version}"\nedition = "2021"\n`,
  );
  writeFileSync(
    join(root, 'src-tauri', 'Cargo.lock'),
    `# autogenerated\r\n[[package]]\r\nname = "hs-offline-tracker"\r\nversion = "${version}"\r\ndependencies = [\r\n]\r\n`,
  );
  writeFileSync(
    join(root, 'package-lock.json'),
    `{\n  "name": "hs-offline-tracker",\n  "version": "${version}",\n  "lockfileVersion": 3,\n  "packages": {\n    "": {\n      "name": "hs-offline-tracker",\n      "version": "${version}",\n      "license": "MIT"\n    }\n  }\n}\n`,
  );
  return root;
}

test('sites() has one entry per site, package-lock.json twice', () => {
  const list = sites();
  assert.equal(list.length, 6);
  const paths = list.map((s) => s.path);
  assert.equal(paths.filter((p) => p === 'package-lock.json').length, 2);
});

test('report() -- every site agrees, no MISSING/MISMATCH', () => {
  const root = makeTree('0.1.3');
  try {
    const { ok, lines } = report(root, '0.1.3');
    assert.equal(ok, true);
    assert.ok(lines.every((l) => !l.includes('MISSING') && !l.includes('MISMATCH')), lines.join('\n'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('report() -- a site holding a different version is MISSING, not silently accepted', () => {
  const root = makeTree('0.1.3');
  try {
    // Drift package-lock.json back to an old version, the way this
    // repository's own tree had drifted before A4.
    const lockPath = join(root, 'package-lock.json');
    writeFileSync(lockPath, readFileSync(lockPath, 'utf8').replaceAll('0.1.3', '0.1.0'));
    const { ok, lines } = report(root, '0.1.3');
    assert.equal(ok, false);
    const missing = lines.filter((l) => l.includes('MISSING'));
    assert.equal(missing.length, 2); // both package-lock.json sites
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('write() -- bumps every site together', () => {
  const root = makeTree('0.1.3');
  try {
    const touched = write(root, '0.1.3', '0.1.4');
    assert.deepEqual(new Set(touched), new Set(['package.json', join('src-tauri', 'tauri.conf.json'), join('src-tauri', 'Cargo.toml'), join('src-tauri', 'Cargo.lock'), 'package-lock.json']));
    const { ok } = report(root, '0.1.4');
    assert.equal(ok, true);
    // The old version is gone everywhere.
    const { ok: oldOk, lines: oldLines } = report(root, '0.1.3');
    assert.equal(oldOk, false, oldLines.join('\n'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('write() -- refuses a half-bumped tree rather than rewriting what matches', () => {
  const root = makeTree('0.1.3');
  try {
    const lockPath = join(root, 'package-lock.json');
    const before = readFileSync(lockPath, 'utf8');
    writeFileSync(lockPath, before.replaceAll('0.1.3', '0.1.0'));

    assert.throws(() => {
      execFileSync(process.execPath, [SCRIPT, '--root', root, '0.1.4'], { stdio: 'pipe' });
    }, /Command failed/);

    // Nothing was rewritten: package.json is still 0.1.3, package-lock.json
    // still holds its drifted 0.1.0.
    const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
    assert.equal(pkg.version, '0.1.3');
    assert.equal(readFileSync(lockPath, 'utf8'), before.replaceAll('0.1.3', '0.1.0'));
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('CLI --check --expect matches this checkout', () => {
  const out = execFileSync(process.execPath, [SCRIPT, '--check', '--expect', '0.1.3'], {
    cwd: new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'),
    encoding: 'utf8',
  });
  assert.ok(!out.includes('MISSING'));
  assert.ok(!out.includes('MISMATCH'));
});

test('CLI --check --expect refuses a version the tree does not hold', () => {
  assert.throws(() => {
    execFileSync(
      process.execPath,
      [SCRIPT, '--check', '--expect', '9.9.9'],
      { cwd: new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'), stdio: 'pipe' },
    );
  }, /Command failed/);
});
